### ISSUE TITLE
Allow customizing breathing steps up to 99s

### ISSUE THREAD

**Issue by rootsh0pf** [mmazzarolo/breathly-app#102]
It would be super nice if you could rise or maybe even remove the limit on the "Hold" times under custom pattern. Like this the app would be perfect for advanced freediving breath hold training. I guess raising the limit from 60 to 99 seconds would be easy and already very helpful. For more than 100 seconds an extra digit would be needed, but then it would be perfect ;)

Anyway thank you for this App, it's beautiful and as it is it's already very useful for me!

**Comment by mmazzarolo** [comment]
Hey there! Holy moly I didn't expect people to hold their breath _this_ much, haha. 
Yeah, this change should be straightforward up to 99 seconds — I think this could be an easy first step and then we can think how to redesign to UI to handle triple digits. 
I also guess it would be nice to be able to hold the decrease/increase buttons instead of tapping it so many times, right? :D

**Comment by rootsh0pf** [comment]
That sounds perfect :)
Offtopic: Haha yeah if you do a session of 5-15 minutes every day and increase the hold time by a few seconds each day you can make impressing progress ;)
