### ISSUE TITLE
Fast switching between breathing techniques

### ISSUE THREAD

**Issue by ropery** [mmazzarolo/breathly-app#53]
Just discovered your app on F-Droid and love it. Thank you!

I'm using version 1.4, the latest on F-Droid, released last November.

The problem: in order to switch to a breathing technique, we have to click a button and leave the main screen, then *swipe* *swipe* left/right, often multiple times, to get to our choice. Then click "back" to return to the main screen.

My proposal: to switch breathing techniques, we click the button, a menu (in whatever shape, design or form) pops up (example item: `4-4-4-4 square`), and we pick one. Done.

Considerations: of course, this would leave out the detailed instructions. How about adding an `(i)` (for instructions/info) button on the main/practice screen to show the instructions of the selected technique?

Thanks again, and hope to see a fresh release on F-Droid soon!

**Comment by mmazzarolo** [comment]
Hey @lolilolicon , thanks for the feedback :) This sounds interesting, but it would require an important rework of the current UI. I'll keep the issue open to see what other people have to say on the matter.  

FYI latest version is 1.8. I'm not maintaining the F-Droid release, someone else published it and I have no idea how to update/bump it.

**Comment by lolilolicon** [comment]
The reason 1.8 is not on F-Droid appears to be their node.js is too old. The [build script](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.mmazzarolo.breathly.yml) is up to date, but for 1.8 says `disable: fails to build nodejs too old`.

**Comment by mmazzarolo** [comment]
Closing. I'm releasing Breathly v2, which fully redesign the app so many issues are not valid anymore.  
In this specific case, the new technique picker doesn't require swiping anymore. That said, it's hidden behind one more tap, so switching is still not as fast as you wanted. 
Since in the previous version I haven't received many complains/asks for making picking the breathing technique "faster", this seems a lower priority issue for now — but we can still re-open it later on if the new interface feels much slower than before.
