### ISSUE TITLE
German and russian translation

### ISSUE THREAD

**Issue by sandoxy** [mmazzarolo/breathly-app#72]
I could help translating the app into german and russian. Is it possible?

**Comment by mmazzarolo** [comment]
Hi! Thanks! It's definitely possible, the issue though is that the guided voice is actually one of the most important parts that should be translated 😞

**Comment by sandoxy** [comment]
@mmazzarolo ok, I guess the sound would be crappy, if I recorded it by myself:) I could try to find somebody with good mic. I know some musicians. And how can I translate the other written parts? Is there a list?

**Comment by mmazzarolo** [comment]
Sorry, I've been a bit busy at work. There's no official list of the text used across the app (yet). Mostly because I haven't worked on multi-language support yet :) 
A good starting point would be creating a list of all the strings (just by writing them down in this GitHub issue, there shouldn't be many of them). 
- Excercise strings are all available in these files: https://github.com/mmazzarolo/breathly-app/tree/master/src/assets/techniques
- Other strings are scattered across the apps, so it's probably easier to just compile a list of them by looking at the app and writing them down in this GitHub issue. 
- Then we have the store descriptions (again, copy-pasting them would be enough). 

Once we have a list, I can work on "centralizing" them, in order to make it easy to support new languages. 
Please be wary that I don't have enough free time to work on this right now, unfortunately, but I might be able to do it in the following months 👍

**Comment by sandoxy** [comment]
Hey, sorry for the delayed answer. Here is the Russian translation. The parts with the yoga-techniques I would translate later. The audio-files are little bit creepy, but I think they are free. I got them from this site: https://voxworker.com/ Maybe there is another service with better voices. But I think the voice attached is ok. One could use the app without voice as well. 

A friend of mine from Russia uses the app in English to recover the lunges from COVID. But there are al lot more Russians, who cannot speak English:)
#########################################
settings = Настройки

custom breathing = Индивидуальное упражнение

back = Назад

dark mode = Тёмный режим
follow system settings = Как в системе
use dark mode = Включить тёмный режим

timer = Таймер
enable exercise timer = Включить таймер
timer duration (minutes) = Длительность таймера (минуты)

vibration = Вибрация
vibrate on step change = Вибрировать при новом этапе

guided breathing = Дыхание с инструктором
disable = Выключить
oksanas voice = Голос Оксаны
bell cue = Колокольчик 

techniques = Техники
custom = Индивидуальная настройка
inhale = Вдох
hold = Держим
exhale = Выдох

relax = Расслабьтесь 

complete = Упражнение завершено
#########################################


[audio.zip](https://github.com/mmazzarolo/breathly-app/files/6748218/audio.zip)

**Comment by mmazzarolo** [comment]
Closing — let's continue the discussion in #62 .
